version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/examples/bq-pusher"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/examples/bq-pusher"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/examples/s3-pusher"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/examples/s3-pusher"
    schedule:
      interval: "weekly"
